import { Activity, ArrowDownRight, CalendarClock, Check, CreditCard, HeartPulse, MapPinned, MessageCircle, ShieldCheck, UserCheck } from 'lucide-react';
import { AppShot, appScreens, Brand, FaqList, LegalFooter, StoreButtons } from '../shared/DesignKit';

const signals = [
  { icon:<MapPinned size={20}/>, tag:'LOCAL', title:'Oportunidades perto e longe', copy:'Explore plantões na lista ou posicione as unidades no mapa.' },
  { icon:<CalendarClock size={20}/>, tag:'TEMPO', title:'Agenda em perspectiva', copy:'Encontre o dia, o período e a duração que combinam com a rotina.' },
  { icon:<UserCheck size={20}/>, tag:'REDE', title:'Médicos verificados', copy:'A comunidade é exclusiva para profissionais com CRM verificado.' },
  { icon:<CreditCard size={20}/>, tag:'REPASSE', title:'Pagamento protegido', copy:'O valor é repassado ao profissional depois da realização do plantão.' },
];

export default function LandingPageTemplate(_: { onGoToApp: () => void }) {
  return <div className="pulse-page" id="top">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Public+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');
      .pulse-page{--pul-ink:#102d3a;--pul-night:#123f4a;--pul-paper:#f5fbfb;--pul-sky:#d5f1f2;--pul-aqua:#46c8c5;--pul-orange:#f49a62;--pul-yellow:#ffd76b;--pul-muted:#537078;--pul-line:rgba(16,45,58,.16);--kit-ink:var(--pul-ink);--kit-muted:var(--pul-muted);--kit-accent:#0b8589;--kit-accent-soft:#76ddd9;--kit-line:var(--pul-line);--kit-focus:var(--pul-yellow);--kit-body:'Public Sans',sans-serif;--kit-utility:'DM Mono',monospace;--kit-frame:var(--pul-night);--kit-radius:1.6rem;--kit-control-radius:1rem;color:var(--pul-ink);background:var(--pul-paper);font-family:'Public Sans',sans-serif;overflow-x:clip}
      .pulse-page *,.pulse-page *::before,.pulse-page *::after{box-sizing:border-box}.pulse-page ::selection{background:var(--pul-yellow);color:var(--pul-ink)}.pulse-shell{width:min(74rem,calc(100% - 3rem));margin:0 auto}
      .pulse-header{position:sticky;top:0;z-index:30;background:rgba(245,251,251,.78);backdrop-filter:blur(22px) saturate(170%);border-bottom:1px solid var(--pul-line)}.pulse-header-inner{min-height:4.7rem;display:flex;align-items:center;justify-content:space-between;gap:2rem}.pulse-nav{display:flex;gap:1.65rem;color:var(--pul-muted);font-size:.74rem;font-weight:700}.pulse-nav a{color:inherit;text-decoration:none}.pulse-cta,.pulse-primary{display:inline-flex;align-items:center;gap:.5rem;padding:.72rem 1rem;color:#fff;background:var(--pul-night);border:1px solid var(--pul-night);border-radius:1rem;text-decoration:none;font-size:.75rem;font-weight:750;transition:transform 180ms cubic-bezier(.23,1,.32,1),background-color 180ms ease}.pulse-cta:active,.pulse-primary:active{transform:scale(.97);transition-duration:160ms}
      .pulse-hero{position:relative;padding:clamp(4.3rem,8vw,7rem) 0 0;background:linear-gradient(180deg,var(--pul-paper),var(--pul-sky));overflow:hidden}.pulse-hero::before{content:'';position:absolute;inset:13rem 0 auto;height:1px;background:var(--pul-line);box-shadow:0 6rem 0 var(--pul-line),0 12rem 0 var(--pul-line)}.pulse-hero-copy{position:relative;z-index:2;max-width:61rem;margin:auto;text-align:center}.pulse-kicker{display:inline-flex;align-items:center;gap:.55rem;margin:0 0 1.25rem;color:#087f83;font:500 .63rem/1 'DM Mono',monospace;letter-spacing:.12em;text-transform:uppercase}.pulse-kicker::before{content:'';width:.55rem;height:.55rem;background:var(--pul-orange);border-radius:50%;box-shadow:0 0 0 .35rem rgba(244,154,98,.16)}.pulse-title{margin:0;font-family:'Space Grotesk',sans-serif;font-size:clamp(3.1rem,7vw,6.8rem);font-weight:650;line-height:.9;letter-spacing:-.075em}.pulse-title span{color:#07858a}.pulse-lede{max-width:43rem;margin:1.65rem auto 0;color:var(--pul-muted);font-size:clamp(.98rem,1.35vw,1.12rem);line-height:1.7}.pulse-actions{display:flex;justify-content:center;flex-wrap:wrap;gap:.8rem;margin-top:2rem}.pulse-link{display:inline-flex;align-items:center;gap:.5rem;padding:.72rem 1rem;color:var(--pul-ink);border:1px solid var(--pul-ink);border-radius:1rem;font-size:.75rem;font-weight:750;text-decoration:none;transition:transform 180ms cubic-bezier(.23,1,.32,1),background-color 180ms ease}.pulse-link:active{transform:scale(.97);transition-duration:160ms}
      .pulse-stage{position:relative;z-index:2;display:grid;grid-template-columns:1fr minmax(18rem,24rem) 1fr;align-items:center;gap:clamp(1rem,4vw,4rem);margin-top:4.5rem;padding-bottom:2rem}.pulse-stage .kit-shot{position:relative;z-index:2}.pulse-stage .kit-shot:nth-of-type(1){transform:translateY(5rem) rotate(-4deg)}.pulse-stage .kit-shot:nth-of-type(2){transform:translateY(5rem) rotate(4deg)}.pulse-center{position:relative;z-index:3;min-height:36rem}.pulse-center .kit-shot{position:absolute;width:100%;inset:0}.pulse-orbit{position:absolute;z-index:5;display:flex;align-items:center;gap:.5rem;padding:.6rem .75rem;color:var(--pul-ink);background:var(--pul-yellow);border:1px solid var(--pul-ink);border-radius:1rem;box-shadow:.35rem .35rem 0 var(--pul-ink);font:600 .62rem/1 'DM Mono',monospace}.pulse-orbit--one{left:-5rem;top:6rem}.pulse-orbit--two{right:-5.5rem;bottom:7rem;background:var(--pul-orange)}
      .pulse-line{position:relative;height:5.5rem;color:#e8f7f7;background:var(--pul-night);overflow:hidden}.pulse-line svg{position:absolute;inset:0;width:100%;height:100%}.pulse-line path{fill:none;stroke:var(--pul-aqua);stroke-width:2;vector-effect:non-scaling-stroke}.pulse-line-inner{position:relative;z-index:2;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:1.2rem;height:100%}.pulse-line strong{color:var(--pul-yellow);font:500 .62rem/1 'DM Mono',monospace;letter-spacing:.1em}.pulse-line p{margin:0;font-family:'Space Grotesk',sans-serif;font-size:clamp(1.05rem,2vw,1.45rem);font-weight:600;letter-spacing:-.035em}
      .pulse-signals{padding:clamp(5rem,9vw,8rem) 0}.pulse-head{display:grid;grid-template-columns:1fr .55fr;gap:4rem;align-items:end;margin-bottom:3.6rem}.pulse-head h2,.pulse-flow-copy h2,.pulse-faq-copy h2,.pulse-download h2{margin:0;font-family:'Space Grotesk',sans-serif;font-size:clamp(2.6rem,5.4vw,5.4rem);font-weight:650;line-height:.92;letter-spacing:-.07em}.pulse-head>p{margin:0;color:var(--pul-muted);font-size:.9rem;line-height:1.7}.pulse-signal-grid{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--pul-line);border-radius:1.8rem;overflow:hidden}.pulse-signal{padding:1.7rem;min-height:17rem;background:#fff}.pulse-signal+.pulse-signal{border-left:1px solid var(--pul-line)}.pulse-signal i{display:grid;width:2.6rem;height:2.6rem;place-items:center;color:var(--pul-night);background:var(--pul-sky);border-radius:.9rem}.pulse-signal code{display:block;margin:2.7rem 0 .7rem;color:#0a8589;font:500 .58rem/1 'DM Mono',monospace;letter-spacing:.1em}.pulse-signal h3{margin:0;font-family:'Space Grotesk',sans-serif;font-size:1.25rem;line-height:1.05;letter-spacing:-.045em}.pulse-signal p{margin:.75rem 0 0;color:var(--pul-muted);font-size:.76rem;line-height:1.55}
      .pulse-flow{padding:clamp(5rem,9vw,8rem) 0;background:var(--pul-sky)}.pulse-flow-grid{display:grid;grid-template-columns:.7fr 1fr;gap:clamp(3rem,8vw,7rem);align-items:center}.pulse-flow-list{margin:2rem 0 0;padding:0;list-style:none}.pulse-flow-list li{display:flex;gap:.7rem;padding:.9rem 0;border-bottom:1px solid var(--pul-line);font-size:.82rem;font-weight:650}.pulse-flow-list svg{color:#087f83;flex:0 0 auto}.pulse-monitor{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:1rem;align-items:end;padding:2rem;border:1px solid var(--pul-night);border-radius:2rem;background:rgba(255,255,255,.45)}.pulse-monitor::before{content:'FLUXO EM TEMPO REAL';position:absolute;top:1rem;left:1.2rem;color:#087f83;font:500 .55rem/1 'DM Mono',monospace;letter-spacing:.1em}.pulse-monitor .kit-shot{margin-top:2rem}.pulse-monitor .kit-shot:last-child{transform:translateY(2rem)}
      .pulse-faq{padding:clamp(5rem,9vw,8rem) 0}.pulse-faq-grid{display:grid;grid-template-columns:.6fr 1fr;gap:clamp(3rem,9vw,8rem)}.pulse-faq-copy p{max-width:21rem;color:var(--pul-muted);line-height:1.65}.pulse-download{position:relative;padding:clamp(4.5rem,8vw,7rem) 0;color:#f0fbfb;background:var(--pul-night);overflow:hidden}.pulse-download::after{content:'';position:absolute;width:34rem;height:34rem;right:-13rem;top:-18rem;border:1px solid rgba(70,200,197,.4);border-radius:50%;box-shadow:0 0 0 4rem rgba(70,200,197,.08),0 0 0 8rem rgba(70,200,197,.05)}.pulse-download-grid{position:relative;z-index:2;display:grid;grid-template-columns:1fr auto;gap:3rem;align-items:center}.pulse-download p{max-width:35rem;color:rgba(240,251,251,.7);line-height:1.65}.pulse-download .kit-stores{margin-top:2rem}.pulse-download-icon{display:grid;width:10rem;height:10rem;place-items:center;color:var(--pul-night);background:var(--pul-aqua);border-radius:2.8rem;transform:rotate(8deg);box-shadow:.8rem .8rem 0 rgba(0,0,0,.22)}.pulse-page a:focus-visible{outline:3px solid var(--pul-yellow);outline-offset:4px}
      @media(hover:hover) and (pointer:fine){.pulse-nav a:hover{color:#07858a}.pulse-cta:hover,.pulse-primary:hover{background:#087f83;transform:translateY(-2px)}.pulse-link:hover{background:var(--pul-yellow);transform:translateY(-2px)}}
      @media(max-width:880px){.pulse-nav{display:none}.pulse-stage{grid-template-columns:1fr 1fr}.pulse-center{grid-column:1/-1;grid-row:1;max-width:22rem;width:100%;margin:auto}.pulse-stage>.kit-shot{display:none}.pulse-head,.pulse-flow-grid,.pulse-faq-grid,.pulse-download-grid{grid-template-columns:1fr}.pulse-signal-grid{grid-template-columns:1fr 1fr}.pulse-signal:nth-child(3){border-left:0;border-top:1px solid var(--pul-line)}.pulse-signal:nth-child(4){border-top:1px solid var(--pul-line)}.pulse-download-icon{display:none}}
      @media(max-width:560px){.pulse-shell{width:min(100% - 1.8rem,74rem)}.pulse-title{font-size:clamp(3.1rem,15vw,4.4rem)}.pulse-stage{margin-top:3rem}.pulse-center{min-height:31rem}.pulse-orbit{display:none}.pulse-signal-grid{grid-template-columns:1fr}.pulse-signal{min-height:auto}.pulse-signal+.pulse-signal{border-left:0;border-top:1px solid var(--pul-line)}.pulse-monitor{gap:.5rem;padding:1rem}.pulse-monitor::before{display:none}.pulse-monitor .kit-shot{margin-top:0}}
      @media(prefers-reduced-motion:reduce){.pulse-cta,.pulse-primary,.pulse-link{transition:color 200ms ease,background-color 200ms ease,opacity 200ms ease}.pulse-cta:hover,.pulse-primary:hover,.pulse-link:hover{transform:none}}
      @media(prefers-reduced-transparency:reduce){.pulse-header{background:var(--pul-paper);backdrop-filter:none}}
    `}</style>
    <header className="pulse-header"><div className="pulse-shell pulse-header-inner"><Brand/><nav className="pulse-nav" aria-label="Navegação principal"><a href="#sinais">Sinais</a><a href="#fluxo">Como funciona</a><a href="#duvidas">Dúvidas</a><a href="?page=sobre-nos">Sobre nós</a></nav><a className="pulse-cta" href="#baixar">Baixar o app <ArrowDownRight size={15}/></a></div></header>
    <main>
      <section className="pulse-hero" aria-labelledby="pulse-title"><div className="pulse-shell"><div className="pulse-hero-copy"><p className="pulse-kicker">Rede médica em atividade</p><h1 className="pulse-title" id="pulse-title">Seu plantão, <span>no ritmo da sua vida.</span></h1><p className="pulse-lede">Encontre oportunidades, organize a agenda ou passe um plantão para médicos verificados — com informação e segurança em cada etapa.</p><div className="pulse-actions"><a className="pulse-primary" href="#baixar">Baixar o app <ArrowDownRight size={16}/></a><a className="pulse-link" href="#sinais">Ver o app em ação <Activity size={16}/></a></div></div><div className="pulse-stage"><AppShot screen={appScreens.mapa}/><div className="pulse-center"><AppShot screen={appScreens.agenda} eager/><span className="pulse-orbit pulse-orbit--one"><MapPinned size={15}/> por proximidade</span><span className="pulse-orbit pulse-orbit--two"><ShieldCheck size={15}/> CRM verificado</span></div><AppShot screen={appScreens.perfil}/></div></div></section>
      <aside className="pulse-line"><svg viewBox="0 0 1200 80" preserveAspectRatio="none" aria-hidden="true"><path d="M0 43h310l20-24 22 45 24-29 22 8h160l18-20 22 37 27-25 20 8h555"/></svg><div className="pulse-shell pulse-line-inner"><strong>SINAL 97</strong><p>A rotina muda. O fluxo continua legível.</p><HeartPulse size={25}/></div></aside>
      <section className="pulse-signals" id="sinais" aria-labelledby="signals-title"><div className="pulse-shell"><div className="pulse-head"><h2 id="signals-title">Quatro sinais para decidir com clareza.</h2><p>O app entrega valor antes de pedir uma decisão: localização, tempo, confiança e repasse aparecem no momento certo.</p></div><div className="pulse-signal-grid">{signals.map(signal=><article className="pulse-signal" key={signal.tag}><i>{signal.icon}</i><code>{signal.tag}</code><h3>{signal.title}</h3><p>{signal.copy}</p></article>)}</div></div></section>
      <section className="pulse-flow" id="fluxo"><div className="pulse-shell pulse-flow-grid"><div className="pulse-flow-copy"><p className="pulse-kicker">Do interesse à confirmação</p><h2>Um fluxo que acompanha a decisão.</h2><ul className="pulse-flow-list"><li><Check size={17}/> Confira todos os detalhes antes de se candidatar.</li><li><Check size={17}/> Acompanhe candidaturas e ofertas no Painel.</li><li><Check size={17}/> Converse com o outro profissional em chat privado.</li><li><Check size={17}/> Use cartão, PIX ou boleto para confirmar.</li></ul></div><div className="pulse-monitor"><AppShot screen={appScreens.detalhes}/><AppShot screen={appScreens.pagamento}/></div></div></section>
      <section className="pulse-faq" id="duvidas"><div className="pulse-shell pulse-faq-grid"><div className="pulse-faq-copy"><p className="pulse-kicker">Sinal aberto</p><h2>Perguntas frequentes.</h2><p>O essencial sobre quem pode entrar, como ofertar, onde encontrar e como o pagamento funciona.</p></div><FaqList/></div></section>
      <section className="pulse-download" id="baixar"><div className="pulse-shell pulse-download-grid"><div><h2>Coloque sua rotina em movimento.</h2><p>Baixe o 97plantões e conecte-se à comunidade médica para encontrar ou passar plantões por todo o Brasil.</p><StoreButtons/></div><span className="pulse-download-icon"><HeartPulse size={64}/></span></div></section>
    </main><LegalFooter inverse/>
  </div>;
}
