import { AlarmClock, ArrowDownRight, CalendarDays, Check, ChevronRight, Clock3, CreditCard, MapPin, ShieldCheck } from 'lucide-react';
import { AppShot, appScreens, Brand, FaqList, LegalFooter, StoreButtons } from '../shared/DesignKit';

const moments = [
  { time:'ANTES', title:'Descubra', copy:'Veja oportunidades na Página Inicial, no Mapa ou na Agenda.', screen:appScreens.inicio, color:'#a9e7d4' },
  { time:'AGORA', title:'Decida', copy:'Confira local, especialidade, data, horário, duração e valor.', screen:appScreens.detalhes, color:'#f4d06f' },
  { time:'DEPOIS', title:'Acompanhe', copy:'Painel, perfil, histórico e recebimentos mantêm a rotina organizada.', screen:appScreens.perfil, color:'#c8c0f2' },
];

export default function LandingPageTemplate(_: { onGoToApp: () => void }) {
  return <div className="compass-page" id="top">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Onest:wght@400;500;600;700&family=Unbounded:wght@500;600;700&display=swap');
      .compass-page{--cmp-ink:#1b2d4f;--cmp-paper:#e9f3fb;--cmp-white:#fbfdff;--cmp-violet:#6759c7;--cmp-mint:#a9e7d4;--cmp-red:#e2584b;--cmp-yellow:#f4d06f;--cmp-muted:#5c6b83;--cmp-line:rgba(27,45,79,.17);--kit-ink:var(--cmp-ink);--kit-muted:var(--cmp-muted);--kit-accent:var(--cmp-violet);--kit-accent-soft:#bdb4ff;--kit-line:var(--cmp-line);--kit-focus:var(--cmp-yellow);--kit-body:'Onest',sans-serif;--kit-utility:'DM Mono',monospace;--kit-frame:var(--cmp-ink);--kit-radius:1.8rem;--kit-control-radius:999px;color:var(--cmp-ink);background:var(--cmp-paper);font-family:'Onest',sans-serif;overflow-x:clip}.compass-page *,.compass-page *::before,.compass-page *::after{box-sizing:border-box}.compass-page ::selection{background:var(--cmp-yellow);color:var(--cmp-ink)}.compass-shell{width:min(74rem,calc(100% - 3rem));margin:0 auto}
      .compass-header{position:sticky;top:0;z-index:30;background:rgba(233,243,251,.8);backdrop-filter:blur(22px) saturate(160%);border-bottom:1px solid var(--cmp-line)}.compass-header-inner{min-height:4.7rem;display:flex;align-items:center;justify-content:space-between;gap:2rem}.compass-nav{display:flex;gap:1.6rem;color:var(--cmp-muted);font-size:.72rem;font-weight:700}.compass-nav a{color:inherit;text-decoration:none}.compass-cta,.compass-primary,.compass-secondary{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;padding:.72rem 1rem;color:#fff;background:var(--cmp-violet);border:1px solid var(--cmp-ink);border-radius:999px;text-decoration:none;font-size:.74rem;font-weight:750;box-shadow:.25rem .25rem 0 var(--cmp-ink);transition:transform 180ms cubic-bezier(.23,1,.32,1),background-color 180ms ease,box-shadow 180ms ease}.compass-secondary{color:var(--cmp-ink);background:var(--cmp-white);box-shadow:none}.compass-cta:active,.compass-primary:active,.compass-secondary:active{transform:scale(.97);box-shadow:none;transition-duration:160ms}
      .compass-hero{position:relative;padding:clamp(4rem,8vw,7rem) 0 5rem;overflow:hidden}.compass-hero::before{content:'';position:absolute;width:44rem;height:44rem;left:-24rem;top:-26rem;border:1px solid rgba(103,89,199,.25);border-radius:50%;box-shadow:0 0 0 4rem rgba(103,89,199,.06),0 0 0 8rem rgba(169,231,212,.15)}.compass-hero-grid{position:relative;display:grid;grid-template-columns:minmax(0,.85fr) minmax(27rem,1.15fr);gap:clamp(3rem,8vw,7rem);align-items:center}.compass-kicker{display:inline-flex;align-items:center;gap:.55rem;margin:0 0 1.3rem;color:var(--cmp-violet);font:500 .63rem/1 'DM Mono',monospace;letter-spacing:.11em;text-transform:uppercase}.compass-kicker::before{content:'';width:.6rem;height:.6rem;background:var(--cmp-red);border-radius:50%}.compass-title{margin:0;font-family:'Unbounded',sans-serif;font-size:clamp(2.9rem,5.7vw,5.7rem);font-weight:650;line-height:.93;letter-spacing:-.065em}.compass-title span{color:var(--cmp-violet)}.compass-lede{max-width:35rem;margin:1.65rem 0 0;color:var(--cmp-muted);font-size:1rem;line-height:1.72}.compass-actions{display:flex;flex-wrap:wrap;gap:.8rem;margin-top:2rem}
      .compass-clock{position:relative;width:min(100%,36rem);aspect-ratio:1;margin:auto;border:1px solid var(--cmp-ink);border-radius:50%;background:var(--cmp-white);box-shadow:1rem 1rem 0 var(--cmp-mint)}.compass-clock::before,.compass-clock::after{content:'';position:absolute;inset:3.2rem;border:1px dashed rgba(27,45,79,.25);border-radius:50%}.compass-clock::after{inset:7rem;border-style:solid}.compass-hour{position:absolute;color:var(--cmp-muted);font:500 .58rem/1 'DM Mono',monospace}.compass-hour--0{top:1.1rem;left:50%;transform:translateX(-50%)}.compass-hour--6{right:1rem;top:50%;transform:translateY(-50%)}.compass-hour--12{bottom:1.1rem;left:50%;transform:translateX(-50%)}.compass-hour--18{left:.8rem;top:50%;transform:translateY(-50%)}.compass-hand{position:absolute;z-index:2;left:50%;bottom:50%;width:2px;height:33%;background:var(--cmp-red);transform-origin:bottom;transform:rotate(42deg)}.compass-hand::before{content:'';position:absolute;width:.75rem;height:.75rem;left:50%;top:-.3rem;background:var(--cmp-red);border-radius:50%;transform:translateX(-50%)}.compass-phone{position:absolute;z-index:4;width:41%;left:29.5%;top:11%;transform:rotate(-2deg)}.compass-phone .kit-shot-frame{box-shadow:.6rem .6rem 0 rgba(27,45,79,.2)}.compass-chip{position:absolute;z-index:6;display:flex;align-items:center;gap:.45rem;padding:.55rem .7rem;color:var(--cmp-ink);background:var(--cmp-yellow);border:1px solid var(--cmp-ink);border-radius:999px;font:600 .6rem/1 'DM Mono',monospace;box-shadow:.25rem .25rem 0 var(--cmp-ink)}.compass-chip--one{left:-1.2rem;top:24%}.compass-chip--two{right:-1.2rem;bottom:23%;background:var(--cmp-mint)}
      .compass-strip{padding:1.05rem 0;color:#fff;background:var(--cmp-ink)}.compass-strip-inner{display:grid;grid-template-columns:auto 1fr auto;gap:1.3rem;align-items:center}.compass-strip code{color:var(--cmp-yellow);font:500 .59rem/1 'DM Mono',monospace;letter-spacing:.1em}.compass-strip p{margin:0;font-family:'Unbounded',sans-serif;font-size:clamp(.95rem,1.8vw,1.3rem);font-weight:550;letter-spacing:-.04em}
      .compass-moments{padding:clamp(5rem,9vw,8rem) 0;background:var(--cmp-white)}.compass-head{display:grid;grid-template-columns:1fr .55fr;gap:4rem;align-items:end;margin-bottom:4rem}.compass-head h2,.compass-control h2,.compass-faq-copy h2,.compass-download h2{margin:0;font-family:'Unbounded',sans-serif;font-size:clamp(2.4rem,4.8vw,4.9rem);font-weight:600;line-height:.94;letter-spacing:-.06em}.compass-head>p{margin:0;color:var(--cmp-muted);font-size:.9rem;line-height:1.7}.compass-moment-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.compass-moment{position:relative;min-height:36rem;padding:1.6rem;overflow:hidden;border:1px solid var(--cmp-ink);border-radius:2rem;background:var(--moment)}.compass-moment code{font:500 .6rem/1 'DM Mono',monospace;letter-spacing:.1em}.compass-moment h3{margin:1.1rem 0 0;font-family:'Unbounded',sans-serif;font-size:clamp(1.5rem,2.5vw,2.3rem);line-height:.95;letter-spacing:-.05em}.compass-moment p{margin:.8rem 0 0;font-size:.78rem;line-height:1.55}.compass-moment .kit-shot{position:absolute;width:70%;left:15%;top:14rem;transform:rotate(3deg)}.compass-moment:nth-child(2) .kit-shot{transform:rotate(-3deg)}.compass-moment-arrow{position:absolute;right:1.2rem;top:1.2rem;display:grid;width:2.5rem;height:2.5rem;place-items:center;border:1px solid var(--cmp-ink);border-radius:50%}
      .compass-control{padding:clamp(5rem,9vw,8rem) 0;background:var(--cmp-paper)}.compass-control-grid{display:grid;grid-template-columns:.7fr 1fr;gap:clamp(3rem,8vw,7rem);align-items:center}.compass-list{margin:2rem 0 0;padding:0;list-style:none}.compass-list li{display:flex;gap:.7rem;padding:.95rem 0;border-bottom:1px solid var(--cmp-line);font-size:.82rem;font-weight:650}.compass-list svg{color:var(--cmp-violet);flex:0 0 auto}.compass-control-stage{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:1rem;align-items:end;padding:2rem 2rem 3rem;border:1px solid var(--cmp-ink);border-radius:50% 50% 2rem 2rem;background:var(--cmp-violet)}.compass-control-stage .kit-shot:last-child{transform:translateY(2rem)}.compass-lock{position:absolute;z-index:5;left:50%;top:48%;display:grid;width:4.8rem;height:4.8rem;place-items:center;color:var(--cmp-ink);background:var(--cmp-yellow);border:1px solid var(--cmp-ink);border-radius:50%;box-shadow:.3rem .3rem 0 var(--cmp-ink);transform:translate(-50%,-50%)}
      .compass-faq{padding:clamp(5rem,9vw,8rem) 0;background:var(--cmp-white)}.compass-faq-grid{display:grid;grid-template-columns:.6fr 1fr;gap:clamp(3rem,9vw,8rem)}.compass-faq-copy p{max-width:21rem;color:var(--cmp-muted);line-height:1.65}.compass-download{padding:clamp(4.5rem,8vw,7rem) 0;color:#fff;background:var(--cmp-violet)}.compass-download-grid{display:grid;grid-template-columns:1fr auto;gap:4rem;align-items:center}.compass-download h2{max-width:50rem}.compass-download p{max-width:35rem;color:rgba(255,255,255,.72);line-height:1.65}.compass-download .kit-stores{margin-top:2rem}.compass-download-clock{display:grid;width:11rem;height:11rem;place-items:center;color:var(--cmp-ink);background:var(--cmp-mint);border:1px solid var(--cmp-ink);border-radius:50%;box-shadow:.8rem .8rem 0 var(--cmp-ink)}.compass-page a:focus-visible{outline:3px solid var(--cmp-yellow);outline-offset:4px}
      @media(hover:hover) and (pointer:fine){.compass-nav a:hover{color:var(--cmp-violet)}.compass-cta:hover,.compass-primary:hover{background:#5547b8;transform:translate(-2px,-2px);box-shadow:.38rem .38rem 0 var(--cmp-ink)}.compass-secondary:hover{background:var(--cmp-yellow);transform:translateY(-2px)}}
      @media(max-width:900px){.compass-nav{display:none}.compass-hero-grid,.compass-head,.compass-control-grid,.compass-faq-grid,.compass-download-grid{grid-template-columns:1fr}.compass-clock{max-width:34rem}.compass-moment-grid{grid-template-columns:1fr;max-width:37rem;margin:auto}.compass-moment{min-height:30rem}.compass-moment .kit-shot{width:min(57%,17rem);left:auto;right:2rem;top:7rem}.compass-download-clock{display:none}}
      @media(max-width:580px){.compass-shell{width:min(100% - 1.8rem,74rem)}.compass-title{font-size:clamp(2.8rem,13.5vw,4rem)}.compass-clock{box-shadow:.5rem .5rem 0 var(--cmp-mint)}.compass-clock::before{inset:2rem}.compass-clock::after{inset:4.5rem}.compass-phone{width:47%;left:26.5%;top:9%}.compass-chip{display:none}.compass-strip-inner{grid-template-columns:1fr auto}.compass-strip code{display:none}.compass-moment{min-height:32rem}.compass-moment .kit-shot{width:68%;right:16%;top:12rem}.compass-control-stage{padding:1rem 1rem 2rem;gap:.5rem}}
      @media(prefers-reduced-motion:reduce){.compass-cta,.compass-primary,.compass-secondary{transition:color 200ms ease,background-color 200ms ease,opacity 200ms ease}.compass-cta:hover,.compass-primary:hover,.compass-secondary:hover{transform:none}}
      @media(prefers-reduced-transparency:reduce){.compass-header{background:var(--cmp-paper);backdrop-filter:none}}
    `}</style>
    <header className="compass-header"><div className="compass-shell compass-header-inner"><Brand/><nav className="compass-nav" aria-label="Navegação principal"><a href="#momentos">A jornada</a><a href="#controle">Seu controle</a><a href="#duvidas">Dúvidas</a><a href="?page=sobre-nos">Sobre nós</a></nav><a className="compass-cta" href="#baixar">Baixar o app <ArrowDownRight size={15}/></a></div></header>
    <main>
      <section className="compass-hero" aria-labelledby="compass-title"><div className="compass-shell compass-hero-grid"><div><p className="compass-kicker">Sua rotina, no centro</p><h1 className="compass-title" id="compass-title">Plantões que respeitam <span>o seu tempo.</span></h1><p className="compass-lede">Encontre oportunidades, passe um plantão quando precisar e acompanhe tudo em uma agenda conectada à sua rotina.</p><div className="compass-actions"><a className="compass-primary" href="#baixar">Baixar o app <ArrowDownRight size={16}/></a><a className="compass-secondary" href="#momentos">Ver a jornada <CalendarDays size={16}/></a></div></div><div className="compass-clock" aria-label="Agenda do app dentro de um mostrador de 24 horas"><span className="compass-hour compass-hour--0">00H</span><span className="compass-hour compass-hour--6">06H</span><span className="compass-hour compass-hour--12">12H</span><span className="compass-hour compass-hour--18">18H</span><i className="compass-hand"/><AppShot className="compass-phone" screen={appScreens.agenda} eager bare/><span className="compass-chip compass-chip--one"><MapPin size={14}/> proximidade</span><span className="compass-chip compass-chip--two"><Clock3 size={14}/> agenda integrada</span></div></div></section>
      <aside className="compass-strip"><div className="compass-shell compass-strip-inner"><code>24 HORAS</code><p>O tempo é seu. O app organiza as possibilidades.</p><AlarmClock size={24}/></div></aside>
      <section className="compass-moments" id="momentos" aria-labelledby="moments-title"><div className="compass-shell"><div className="compass-head"><h2 id="moments-title">Antes, agora e depois do plantão.</h2><p>A ordem é parte do design: descubra primeiro, decida com contexto e acompanhe o que foi confirmado.</p></div><div className="compass-moment-grid">{moments.map(moment=><article className="compass-moment" style={{'--moment':moment.color} as React.CSSProperties} key={moment.time}><code>{moment.time}</code><span className="compass-moment-arrow"><ChevronRight size={18}/></span><h3>{moment.title}</h3><p>{moment.copy}</p><AppShot screen={moment.screen}/></article>)}</div></div></section>
      <section className="compass-control" id="controle"><div className="compass-shell compass-control-grid"><div><p className="compass-kicker">Controle com segurança</p><h2>Seu tempo, sua escolha, um fluxo protegido.</h2><ul className="compass-list"><li><Check size={17}/> Ofertar um plantão é gratuito.</li><li><Check size={17}/> Você escolhe quem vai assumir após revisar o perfil.</li><li><Check size={17}/> O chat privado ajuda a alinhar os detalhes.</li><li><Check size={17}/> O repasse acontece depois da realização do plantão.</li></ul></div><div className="compass-control-stage"><AppShot screen={appScreens.ofertas}/><AppShot screen={appScreens.pagamento}/><span className="compass-lock"><ShieldCheck size={27}/></span></div></div></section>
      <section className="compass-faq" id="duvidas"><div className="compass-shell compass-faq-grid"><div className="compass-faq-copy"><p className="compass-kicker">No seu tempo</p><h2>Perguntas frequentes.</h2><p>Informação direta para planejar o próximo passo sem pressa nem surpresa.</p></div><FaqList/></div></section>
      <section className="compass-download" id="baixar"><div className="compass-shell compass-download-grid"><div><h2>Seu próximo plantão começa quando fizer sentido.</h2><p>Baixe o 97plantões para explorar oportunidades e organizar a rotina com médicos verificados por todo o Brasil.</p><StoreButtons/></div><span className="compass-download-clock"><AlarmClock size={67}/></span></div></section>
    </main><LegalFooter inverse/>
  </div>;
}
