import { ArrowDownRight, ArrowUpRight, Check, CreditCard, Eye, Map, ShieldCheck, UserRound } from 'lucide-react';
import { AppShot, appScreens, Brand, FaqList, LegalFooter, StoreButtons } from '../shared/DesignKit';

export default function LandingPageTemplate(_: { onGoToApp: () => void }) {
  return <div className="window-page" id="top">
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&family=IBM+Plex+Mono:wght@400;500&family=Syne:wght@600;700;800&display=swap');
      .window-page{--win-ink:#101820;--win-paper:#fff;--win-blue:#1553a4;--win-cyan:#42b7c6;--win-yellow:#f6da69;--win-red:#ed6e5c;--win-mist:#eaf3f7;--win-muted:#5f6d77;--win-line:rgba(16,24,32,.18);--kit-ink:var(--win-ink);--kit-muted:var(--win-muted);--kit-accent:var(--win-blue);--kit-accent-soft:#79d2dd;--kit-line:var(--win-line);--kit-focus:var(--win-yellow);--kit-body:'DM Sans',sans-serif;--kit-utility:'IBM Plex Mono',monospace;--kit-frame:var(--win-ink);--kit-radius:0;--kit-control-radius:0;color:var(--win-ink);background:var(--win-paper);font-family:'DM Sans',sans-serif;overflow-x:clip}.window-page *,.window-page *::before,.window-page *::after{box-sizing:border-box}.window-page ::selection{background:var(--win-yellow);color:var(--win-ink)}.window-shell{width:min(76rem,calc(100% - 3rem));margin:0 auto}
      .window-header{position:sticky;top:0;z-index:30;background:rgba(255,255,255,.84);backdrop-filter:blur(20px) saturate(160%);border-bottom:1px solid var(--win-line)}.window-header-inner{min-height:4.65rem;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:2rem}.window-nav{display:flex;gap:1.5rem;color:var(--win-muted);font-size:.72rem;font-weight:650}.window-nav a{color:inherit;text-decoration:none}.window-header .kit-brand{justify-self:center}.window-cta{justify-self:end;display:inline-flex;align-items:center;gap:.5rem;padding:.72rem 1rem;color:#fff;background:var(--win-blue);border:1px solid var(--win-ink);font-size:.73rem;font-weight:750;text-decoration:none;box-shadow:.28rem .28rem 0 var(--win-ink);transition:transform 180ms cubic-bezier(.23,1,.32,1),background-color 180ms ease,box-shadow 180ms ease}.window-cta:active{transform:scale(.97);box-shadow:none;transition-duration:160ms}
      .window-hero{position:relative;padding:clamp(4.5rem,8vw,7.5rem) 0 5rem;border-bottom:1px solid var(--win-ink)}.window-hero::before{content:'97';position:absolute;right:-.08em;top:-.18em;color:rgba(21,83,164,.055);font:800 min(39vw,38rem)/1 'Syne',sans-serif;letter-spacing:-.12em}.window-hero-grid{position:relative;display:grid;grid-template-columns:minmax(0,.8fr) minmax(29rem,1.2fr);gap:clamp(3rem,8vw,7rem);align-items:center}.window-kicker{display:flex;align-items:center;gap:.65rem;margin:0 0 1.35rem;color:var(--win-blue);font:500 .63rem/1 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase}.window-kicker::before{content:'';width:2rem;height:4px;background:var(--win-red)}.window-title{margin:0;font-family:'Syne',sans-serif;font-size:clamp(3.4rem,6.6vw,6.8rem);font-weight:750;line-height:.85;letter-spacing:-.075em}.window-title span{color:var(--win-blue);text-decoration:underline;text-decoration-color:var(--win-yellow);text-decoration-thickness:.13em;text-underline-offset:.08em}.window-lede{max-width:35rem;margin:1.65rem 0 0;color:var(--win-muted);font-size:1rem;line-height:1.7}.window-actions{display:flex;flex-wrap:wrap;gap:.8rem;margin-top:2rem}.window-primary,.window-secondary{display:inline-flex;align-items:center;gap:.5rem;padding:.8rem 1rem;color:#fff;background:var(--win-ink);border:1px solid var(--win-ink);font-size:.76rem;font-weight:750;text-decoration:none;transition:transform 180ms cubic-bezier(.23,1,.32,1),background-color 180ms ease}.window-secondary{color:var(--win-ink);background:var(--win-yellow)}.window-primary:active,.window-secondary:active{transform:scale(.97);transition-duration:160ms}
      .window-stage{position:relative;display:grid;grid-template-columns:.83fr 1.17fr;grid-template-rows:14rem 17rem;gap:.8rem;min-height:32rem}.window-pane{position:relative;overflow:hidden;border:1px solid var(--win-ink);background:var(--win-mist)}.window-pane--tall{grid-row:1/-1}.window-pane--blue{background:var(--win-blue);}.window-pane .kit-shot{position:absolute;width:83%;left:8.5%;top:1.8rem}.window-pane--tall .kit-shot{width:86%;left:7%;top:2rem}.window-pane--blue .kit-shot{width:53%;left:24%;top:2rem}.window-pane-label{position:absolute;z-index:4;left:.65rem;bottom:.65rem;padding:.4rem .5rem;color:var(--win-ink);background:var(--win-yellow);border:1px solid var(--win-ink);font:500 .55rem/1 'IBM Plex Mono',monospace;text-transform:uppercase;letter-spacing:.07em}.window-stage-badge{position:absolute;z-index:7;left:34%;top:45%;display:grid;width:5rem;height:5rem;place-items:center;color:#fff;background:var(--win-red);border:1px solid var(--win-ink);border-radius:50%;box-shadow:.35rem .35rem 0 var(--win-ink)}
      .window-statement{padding:1.3rem 0;background:var(--win-yellow);border-bottom:1px solid var(--win-ink)}.window-statement-inner{display:grid;grid-template-columns:auto 1fr auto;gap:1.3rem;align-items:center}.window-statement code{font:500 .58rem/1 'IBM Plex Mono',monospace;letter-spacing:.08em}.window-statement p{margin:0;font-family:'Syne',sans-serif;font-size:clamp(1.1rem,2.2vw,1.55rem);font-weight:700;letter-spacing:-.04em}
      .window-scenes{padding:clamp(5rem,10vw,9rem) 0;background:var(--win-mist)}.window-head{display:grid;grid-template-columns:1fr .55fr;gap:4rem;align-items:end;margin-bottom:4rem}.window-head h2,.window-trust h2,.window-faq-copy h2,.window-download h2{margin:0;font-family:'Syne',sans-serif;font-size:clamp(2.7rem,5.5vw,5.6rem);font-weight:750;line-height:.88;letter-spacing:-.07em}.window-head>p{margin:0;color:var(--win-muted);line-height:1.7}.window-wall{display:grid;grid-template-columns:1.2fr .8fr;grid-template-rows:auto auto;border:1px solid var(--win-ink)}.window-scene{position:relative;display:grid;grid-template-columns:.7fr 1fr;gap:2.2rem;min-height:31rem;padding:clamp(1.5rem,3.5vw,3rem);overflow:hidden;background:#fff}.window-scene:nth-child(2){grid-template-columns:1fr;background:var(--win-yellow);border-left:1px solid var(--win-ink)}.window-scene:nth-child(3){grid-column:1/-1;grid-template-columns:1fr 1fr;min-height:28rem;background:var(--win-blue);color:#fff;border-top:1px solid var(--win-ink)}.window-scene-copy{position:relative;z-index:3}.window-scene code{color:var(--win-red);font:500 .6rem/1 'IBM Plex Mono',monospace;letter-spacing:.1em}.window-scene:nth-child(3) code{color:var(--win-yellow)}.window-scene h3{margin:1rem 0 0;font-family:'Syne',sans-serif;font-size:clamp(2rem,4vw,3.8rem);line-height:.9;letter-spacing:-.06em}.window-scene p{max-width:27rem;margin:1rem 0 0;color:var(--win-muted);font-size:.83rem;line-height:1.65}.window-scene:nth-child(3) p{color:rgba(255,255,255,.72)}.window-scene .kit-shot{width:min(100%,17rem);align-self:end;justify-self:center}.window-scene:nth-child(2) .kit-shot{width:min(70%,15rem);margin-top:1.5rem}.window-scene:nth-child(3) .kit-shot{width:min(65%,17rem);transform:rotate(2deg)}
      .window-trust{padding:clamp(5rem,9vw,8rem) 0}.window-trust-grid{display:grid;grid-template-columns:.7fr 1fr;gap:clamp(3rem,8vw,7rem);align-items:center}.window-checks{display:grid;grid-template-columns:1fr 1fr;gap:0;margin:2rem 0 0;padding:0;list-style:none;border:1px solid var(--win-line)}.window-checks li{display:flex;gap:.65rem;padding:1rem;font-size:.78rem;font-weight:650}.window-checks li:nth-child(odd){border-right:1px solid var(--win-line)}.window-checks li:nth-child(n+3){border-top:1px solid var(--win-line)}.window-checks svg{color:var(--win-blue);flex:0 0 auto}.window-quote{position:relative;padding:clamp(2rem,5vw,4rem);color:#fff;background:var(--win-ink);border:1px solid var(--win-ink);box-shadow:1rem 1rem 0 var(--win-cyan)}.window-quote::before{content:'“';position:absolute;right:1rem;top:-1.4rem;color:var(--win-yellow);font:800 9rem/1 'Syne',sans-serif}.window-quote blockquote{position:relative;margin:0;font-family:'Syne',sans-serif;font-size:clamp(1.5rem,2.8vw,2.4rem);line-height:1.08;letter-spacing:-.045em}.window-quote footer{margin-top:2rem;color:rgba(255,255,255,.65);font:500 .62rem/1.5 'IBM Plex Mono',monospace;text-transform:uppercase;letter-spacing:.06em}
      .window-faq{padding:clamp(5rem,9vw,8rem) 0;background:var(--win-mist);border-top:1px solid var(--win-ink)}.window-faq-grid{display:grid;grid-template-columns:.58fr 1fr;gap:clamp(3rem,9vw,8rem)}.window-faq-copy p{max-width:20rem;color:var(--win-muted);line-height:1.65}.window-download{padding:clamp(4.5rem,8vw,7rem) 0;color:#fff;background:var(--win-blue)}.window-download-grid{display:grid;grid-template-columns:1fr auto;gap:4rem;align-items:center}.window-download h2{max-width:50rem}.window-download p{max-width:34rem;color:rgba(255,255,255,.72);line-height:1.65}.window-download .kit-stores{margin-top:2rem}.window-open{display:grid;width:10rem;height:10rem;place-items:center;color:var(--win-ink);background:var(--win-yellow);border:1px solid var(--win-ink);font-family:'Syne',sans-serif;font-size:2rem;font-weight:800;box-shadow:.8rem .8rem 0 var(--win-ink)}.window-page a:focus-visible{outline:3px solid var(--win-yellow);outline-offset:4px}
      @media(hover:hover) and (pointer:fine){.window-nav a:hover{color:var(--win-blue)}.window-cta:hover{transform:translate(-2px,-2px);box-shadow:.4rem .4rem 0 var(--win-ink)}.window-primary:hover{background:var(--win-blue);transform:translateY(-2px)}.window-secondary:hover{background:#ffe994;transform:translateY(-2px)}}
      @media(max-width:900px){.window-header-inner{grid-template-columns:1fr auto}.window-header .kit-brand{justify-self:start}.window-nav{display:none}.window-hero-grid,.window-head,.window-trust-grid,.window-faq-grid,.window-download-grid{grid-template-columns:1fr}.window-stage{width:100%;max-width:38rem;margin:0 auto}.window-wall{grid-template-columns:1fr}.window-scene:nth-child(2){border-left:0;border-top:1px solid var(--win-ink)}.window-open{display:none}}
      @media(max-width:600px){.window-shell{width:min(100% - 1.8rem,76rem)}.window-title{font-size:clamp(3.3rem,16vw,4.7rem)}.window-stage{grid-template-columns:1fr 1fr;grid-template-rows:12rem 14rem;min-height:27rem}.window-stage-badge{left:41%;width:4rem;height:4rem}.window-pane--blue .kit-shot{width:66%;left:17%}.window-scene,.window-scene:nth-child(3){grid-template-columns:1fr;min-height:auto}.window-scene .kit-shot,.window-scene:nth-child(2) .kit-shot,.window-scene:nth-child(3) .kit-shot{width:min(70%,15rem);margin:2rem auto 0}.window-checks{grid-template-columns:1fr}.window-checks li:nth-child(odd){border-right:0}.window-checks li+li{border-top:1px solid var(--win-line)}}
      @media(prefers-reduced-motion:reduce){.window-cta,.window-primary,.window-secondary{transition:color 200ms ease,background-color 200ms ease,opacity 200ms ease}.window-cta:hover,.window-primary:hover,.window-secondary:hover{transform:none}}
      @media(prefers-reduced-transparency:reduce){.window-header{background:#fff;backdrop-filter:none}}
    `}</style>
    <header className="window-header"><div className="window-shell window-header-inner"><nav className="window-nav" aria-label="Navegação principal"><a href="#produto">O produto</a><a href="#confianca">Confiança</a><a href="#duvidas">Dúvidas</a></nav><Brand/><a className="window-cta" href="#baixar">Abrir o app <ArrowUpRight size={15}/></a></div></header>
    <main>
      <section className="window-hero" aria-labelledby="window-title"><div className="window-shell window-hero-grid"><div><p className="window-kicker">O produto em primeiro plano</p><h1 className="window-title" id="window-title">Veja tudo. <span>Decida melhor.</span></h1><p className="window-lede">O 97plantões conecta médicos a oportunidades por todo o Brasil e mostra o que importa antes de uma candidatura ou passagem de plantão.</p><div className="window-actions"><a className="window-primary" href="#baixar">Baixar o app <ArrowDownRight size={16}/></a><a className="window-secondary" href="#produto">Ver telas reais <Eye size={16}/></a></div></div><div className="window-stage"><div className="window-pane window-pane--tall"><AppShot screen={appScreens.inicio} eager bare/><span className="window-pane-label">Oportunidades</span></div><div className="window-pane window-pane--blue"><AppShot screen={appScreens.mapa} eager bare/><span className="window-pane-label">Mapa</span></div><div className="window-pane"><AppShot screen={appScreens.agenda} eager bare/><span className="window-pane-label">Agenda</span></div><span className="window-stage-badge"><Eye size={27}/></span></div></div></section>
      <aside className="window-statement"><div className="window-shell window-statement-inner"><code>VISÃO 01</code><p>Não escondemos o produto atrás da promessa.</p><ArrowUpRight size={23}/></div></aside>
      <section className="window-scenes" id="produto" aria-labelledby="window-scenes-title"><div className="window-shell"><div className="window-head"><h2 id="window-scenes-title">Três janelas para uma decisão completa.</h2><p>As telas reais organizam descoberta, confirmação e controle sem inventar estatísticas ou atalhos.</p></div><div className="window-wall"><article className="window-scene"><div className="window-scene-copy"><code>01 / DESCOBRIR</code><h3>Oportunidades com contexto.</h3><p>Compare especialidade, unidade, data, horário, duração e valor. Use a lista, o mapa ou a agenda.</p></div><AppShot screen={appScreens.detalhes}/></article><article className="window-scene"><div className="window-scene-copy"><code>02 / ORGANIZAR</code><h3>Painel para acompanhar.</h3><p>Ofertas, candidaturas e confirmações continuam acessíveis no fluxo.</p></div><AppShot screen={appScreens.ofertas}/></article><article className="window-scene"><div className="window-scene-copy"><code>03 / CONFIRMAR</code><h3>Pagamento com o responsável à vista.</h3><p>Cartão de crédito, PIX e boleto. O valor fica protegido e o repasse ocorre somente após a realização do plantão.</p></div><AppShot screen={appScreens.pagamento}/></article></div></div></section>
      <section className="window-trust" id="confianca"><div className="window-shell window-trust-grid"><div><p className="window-kicker">Segurança em primeiro lugar</p><h2>O que você vê sustenta a confiança.</h2><ul className="window-checks"><li><Check size={16}/> CRM verificado</li><li><Check size={16}/> Dados protegidos</li><li><Check size={16}/> Chat privado</li><li><Check size={16}/> Repasse após o plantão</li></ul></div><div className="window-quote"><blockquote>“Encontrar plantões na minha especialidade ficou muito mais fácil. O mapa interativo é incrível para encontrar plantões em hospitais próximos a mim.”</blockquote><footer>Pediatra · Rio de Janeiro, RJ · Médica verificada</footer></div></div></section>
      <section className="window-faq" id="duvidas"><div className="window-shell window-faq-grid"><div className="window-faq-copy"><p className="window-kicker">Ainda olhando?</p><h2>Vale saber.</h2><p>Respostas objetivas sobre cadastro, oferta, descoberta e pagamento.</p></div><FaqList/></div></section>
      <section className="window-download" id="baixar"><div className="window-shell window-download-grid"><div><h2>Abra a próxima janela no app.</h2><p>Baixe o 97plantões para encontrar ou passar plantões com médicos verificados, segurança e eficiência.</p><StoreButtons/></div><span className="window-open">97<ArrowUpRight size={25}/></span></div></section>
    </main><LegalFooter inverse/>
  </div>;
}
